name = "resume-expert11"
compatibility_date = "2026-07-20"

[[d1_databases]]
binding = "DB"
database_name = "resume-expert-db"
database_id = "60006f59-fcd1-46af-bcb6-deb083c69804"

[vars]
AI_MODE = "deepseek"
DEEPSEEK_MODEL = "deepseek-chat"
PRICE_MARKUP = "1.4"
